database:
  host: db2204.laser2mail.com
  port: 5432
  user: londen
  password: FuseMind2024
  name: londen-local

app:
  secret_key: your_secret_key_here

ftp:
  hostname: localhost
  port: 22
  username: sftpuser
  password: MyPassword123
  remote_dir: /var/ftp/secure/londen-policy/Campaign_Manager